/*
 * PantallaPrincipal.java
 *
 * Created on 03-nov-2010, 13:35:37
 */

package servidorapache;

/**
 *
 * @author Ricardo Jose Alvarado Villalobos
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    ///Variables Globales:
    boolean servidor_activado;
    Servidor servidor;

    /** Creates new form PantallaPrincipal */
    public PantallaPrincipal() {
        initComponents();
        servidor_activado = false;
        this.desplegar("Servidor Simple v.1.0\nElaborado por Ricardo Alvarado\n2010");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_informacion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        boton_activacion = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor Web - Ricardo Alvarado A60289");
        setName("PantallaPrincipal"); // NOI18N

        jPanel1.setName("PantallaPrincipal"); // NOI18N

        jTextArea_informacion.setColumns(20);
        jTextArea_informacion.setRows(5);
        jScrollPane1.setViewportView(jTextArea_informacion);

        jLabel1.setText("Acciones del Servidor:");

        boton_activacion.setText("Click Para Activar");
        boton_activacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_activacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(boton_activacion, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_activacion))
                .addContainerGap())
        );

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        jMenuItem2.setText("Acerca De");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Servidor Web - Ricardo Alvarado A60289");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    


    private void boton_activacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_activacionActionPerformed
        if (!servidor_activado)
        {
            try {
                this.desplegar("\nIniciando...\n");
                servidor = new Servidor (this, this.get_path_por_sistema_operativo());
                servidor_activado = true;
                boton_activacion.setText("Click para Desactivar");
            }
            catch (Exception e) {
                e.printStackTrace();
                System.exit(1);
            }
        }
        else
        {
            try {
                this.desplegar("\nDeteniendo...\n");
                servidor.desactivarServidor();
                servidor = null;
                servidor_activado = false;
                boton_activacion.setText("Click para Activar");
                this.desplegar("Detenido\n");
            }
            catch (Exception e) {
                e.printStackTrace();
                System.exit(1);
            }
        }
    }//GEN-LAST:event_boton_activacionActionPerformed

    public void desplegar(String texto)
    {
        String s = jTextArea_informacion.getText();
        s = s + texto + "\n";
        jTextArea_informacion.setText(s);
    }

    private String get_path_por_sistema_operativo(){
        String respuesta = ""; //1 = mac, 2 = windows, 3 = linux

        String os = System.getProperty("os.name" );
        os = os.toLowerCase();
        if(os.contains("mac")){
            respuesta = "/www/configuracion.xml";
        }else if (os.contains("win")){
            respuesta = "c:/www/configuracion.xml";
        }else if(os.contains("nix")){
            respuesta = "/www/configuracion.xml";
        }
        return (respuesta);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        AcercaDe acerca = new AcercaDe();
        acerca.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton boton_activacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_informacion;
    // End of variables declaration//GEN-END:variables

}
